[theme]
base = "dark"
primaryColor = "#BAD6EB"
backgroundColor = "#081F5C"
secondaryBackgroundColor = "#334EAC"
textColor = "#FFF9F0"
font = "sans-serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
